version: "3.1"
services:

  db:
    image: postgres:9.4
    
    secrets:
      - db_username
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE:  /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_username
      
secrets:
  db_username:
    file: ./postgres_user.txt
  db_password:
    file: ./postgres_password.txt